// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("$projectname$")]
[assembly: AssemblyCopyright("Copyright © $year$ John Gietzen")]
[assembly: ComVisible(false)]
