// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("6b1d5590-7cec-4fb0-a0e1-1dd7a43d94ad")]
[assembly: CLSCompliant(false)]
[assembly: InternalsVisibleTo("Farkle.Tests")]
