// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("$guid4$")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("$projectname$.Tests")]
